# Generated by Django 4.1.1 on 2022-09-08 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('discounted_price', models.IntegerField(blank=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], max_length=200)),
                ('short_description', models.TextField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('stock', models.CharField(choices=[('In Stock', 'In Stock'), ('Out of stock', 'Out of stock')], max_length=100)),
                ('image', models.TextField()),
                ('labels', models.CharField(max_length=200)),
            ],
        ),
    ]
