# Generated by Django 4.1.1 on 2022-09-12 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_item_category_item_subcategory_subcategory_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='status',
            field=models.CharField(blank=True, choices=[('active', 'Active'), ('inactive', 'Inactive'), ('', 'Default')], max_length=200),
        ),
        migrations.AlterField(
            model_name='ad',
            name='rank',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='discounted_price',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
